Update branch name validation messages

diff --git a/.github/workflows/branch-name-check.yml b/.github/workflows/branch-name-check.yml
--- a/.github/workflows/branch-name-check.yml
+++ b/.github/workflows/branch-name-check.yml
@@ -32,7 +32,7 @@ jobs:
       if: ${{ steps.branch-names.outputs.base_ref_branch == 'develop' }}
       run: |
         if ! [[ "${{ steps.branch-names.outputs.head_ref_branch }}" =~ ^(feature/.*|docs/.*|hotfix/.*|bugfix/.*|release/[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?)$ ]]; then
-          echo "reason=Invalid branch name for develop. Branches must follow the GitFlow naming convention." >> $GITHUB_OUTPUT
+          echo "reason=Invalid branch name for ${{ steps.branch-names.outputs.base_ref_branch }}. Branches must follow the GitFlow naming convention." >> $GITHUB_OUTPUT
         fi
 
     - name: Check branch name for main PRs
@@ -40,11 +40,24 @@ jobs:
       if: ${{ steps.branch-names.outputs.base_ref_branch == 'main' }}
       run: |
         if ! [[ "${{ steps.branch-names.outputs.head_ref_branch }}" =~ ^(hotfix/.*|release/[0-9]+\.[0-9]+\.[0-9]+(rc[0-9]+)?)$ ]]; then
-          echo "reason=Invalid branch name for main. Pull requests must be from a hotfix or release branch." >> $GITHUB_OUTPUT
+          echo "reason=Invalid branch name for ${{ steps.branch-names.outputs.base_ref_branch }}. Pull requests must be from a hotfix or release branch." >> $GITHUB_OUTPUT
         fi
 
-    - name: Comment on PR for invalid branch name
+    - name: Check for existing comment
       if: ${{ steps.check-develop-branch.outputs.reason || steps.check-main-branch.outputs.reason }}
+      id: check-comment
+      run: |
+        commentExists=$(gh pr view ${{ github.event.pull_request.number }} --json comments -q '.comments[].body' | grep -F "Invalid branch name" || echo '')
+        if [[ -n "$commentExists" ]]; then
+          echo "commentExists=true" >> $GITHUB_OUTPUT
+        else
+          echo "commentExists=false" >> $GITHUB_OUTPUT
+        fi
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+    - name: Comment on PR for invalid branch name
+      if: steps.check-comment.outputs.commentExists == 'false'
       run: |
         reason="${{ steps.check-develop-branch.outputs.reason }}${{ steps.check-main-branch.outputs.reason }}"
         gh pr comment ${{ github.event.pull_request.number }} --body "$reason Please review our [branch naming guidelines](LINK_TO_GUIDELINES)."
